### PR TITLE
Cleaning up

### PR DESCRIPTION
**Pull request by TheWildBear**
**Cleaning up**
Is that okay, or did I miss some lines?
Should I ask a friend if he can check the Chinese stuff for us?

### CODE REVIEW

**Comment by TheWildBear** [comment]
Could someone check if the update channel is everywhere __removed__ ?

**Comment by lftkv** [comment]
Is it necessary to keep all languages? I think only English would be sufficient

**Comment by TheWildBear** [comment]
Interesting idea. That would shrink down the memory allocated and _should_  help improving the response time. 

When we choose this route we should include :
1. Clean up of languages
2. Removal of unnecessary code
3. Maybe code revamp?

**Comment by TheWildBear** [comment]
Delete the unnessery languages first as discussed

**Pull request closed without merging**
